### ISSUE TITLE
启动提示初始化失败

### ISSUE THREAD

**Issue by onming** [plter/FreeScreenRecorder#4]
![image](https://user-images.githubusercontent.com/3692010/58145481-d609bb00-7c84-11e9-8bde-18e200d06f90.png)

查看控制台好像也没报什么错误

**Comment by onming** [comment]
这软件必须要装个摄像头才能录制吗。

**Comment by plter** [comment]
不用摄像头，你需要打开开发者工具面板查看输出信息。

**Comment by onming** [comment]
好像控制台也没错误提示

**Comment by plter** [comment]
![Screen Shot 2019-05-22 at 8 40 45 PM](https://user-images.githubusercontent.com/4636003/58175242-4d197080-7cd2-11e9-9615-ac547ce437cc.png)
这里是有输出的，至于如何使用electron技术，请参考我的JavaScript全栈课程第15章，[http://yunp.top/init/p/v/1#video_id=608](http://yunp.top/init/p/v/1#video_id=608)

**Comment by onming** [comment]
好的谢谢，可能我是用npm来运行的没看到错误日志。alert是可以打印出来提示是
![image](https://user-images.githubusercontent.com/3692010/58175496-d0d35d00-7cd2-11e9-9263-f9b0b4ffaa5f.png)
